export const brandNames = {
  'theknitcompany.com': '더니트컴퍼니',
  'fatalism.co.kr': '페이탈리즘',
  'partsstore.kr': '파츠',
  'garment-lable.com': '가먼트레이블',
  'bananafit.co.kr': '바나나핏',
  '86road.co.kr': '86로드',
  'lohnt.co.kr': '론트',
  'notnnot.com': '낫앤낫',
  'hance.kr': '핸스',
  'maison-mined.com': '메종미네드',
  'maisonmargiela.com': '메종 마르지엘라',
  'modnine.com': '모드나인',
  'pavement.co.kr': '페이브먼트',
  'flareup.co.kr': '플레어업',
  'coor.kr': '쿠어',
  'espionage.co.kr': '에스피오나지',
  'afterpray.com': '애프터프레이',
  'carhartt-wip.co.kr': '칼하트',
  'nbkorea.com': '뉴발란스',
  'newbalance.com': '뉴발란스',
  'converse.co.kr': '컨버스',
  'asics.com': '아식스',
  'personal-pack.com': '퍼스널팩',
  'zavanas.com': '자바나스',
  'lmood.co.kr': '엘무드',
  'tonywack.com': '토니웩',
  'cosstores.com': '코스',
  'plac-official.com': '플랙',
  'giordano.co.kr': '지오다노',
  'lafudgestore.com': '라퍼지스토어',
  'insilence.co.kr': '인사일런스',
  'draw-fit.com': '드로우핏',
  'buttonseoul.com': '버튼서울',
  'store-kr.uniqlo.com': '유니클로',
  'spao.elandmall.com': '스파오',
  'www2.hm.com': 'H&M',
  'u-ping.co.kr': '유핑',
  'romanticpirates.com': '로맨틱파이어리츠',
  'shop2.ubridge001.cafe24.com': '유니폼브릿지',
  'yupwear.co.kr': '여피',
  '6ft.co.kr': '식스핏',
  'shoopen.elandmall.com': '슈펜',
  'jemutshop.com': '제멋',
  'mahagrid.com': '마하그리드',
  'whoisnerdy.com': '널디',
  'vivastudio.co.kr': '비바스튜디오',
  'romanticcrown.com': '로맨틱크라운',
  'stussy.co.kr': '스투시',
  'iamnotahumanbeing.com': '아임낫어휴먼비잉',
  'esnocturne.com': '이에스엔',
  'kr.puma.com': '푸마',
  'fila.co.kr': '휠라',
  'shop.adidas.co.kr': '아디다스',
  'zara.com': '자라',
  'shop.vans.co.kr': '반스',
  'drmartens.co.kr': '닥터마틴',
  'levi.co.kr': '리바이스',
  'discovery-expedition.com': '디스커버리 익스페디션',
  'kirsh.co.kr': '키르시',
  'dunststudio.com': '던스트',
  'urbanstoff.com': '어반스터프',
  'minav.co.kr': '미나브',
  'modified.co.kr': '모디파이드',
  'beyondcloset.com': '비욘드클로젯',
  'leire.co.kr': '르아르',
  'ordinarypeople.co.kr': '오디너리피플',
  'bants.co.kr': '반츠',
  'mlb-korea.com': 'MLB',
  'add-seoul.com': '에드',
  'doffjason.co.kr': '도프제이슨',
  'filluminate.com': '필루미네이트',
  'istkunst.co.kr': '이스트쿤스트',
  'thet-shirtmuseum.com': '더티셔츠뮤지엄',
  'milletclassic.com': '밀레클래식',
  'crump.co.kr': '크럼프',
  'morelab.cafe24.com': '오베르',
  'xeroxero.co.kr': '제로',
  'frizm.co.kr': '프리즘웍스',
  'tngt.co.kr': 'tngt',
  'toffee.co.kr': '토피',
  'massnoun.com': '매스노운',
  'josepht.co.kr': '조셉트',
  'sperone.co.kr': '스페로네',
  'lab-101.com': '랩101',
  'uniformbridge.co.kr': '유니폼브릿지',
  'inrows.co.kr': '인로우스',
  'lambyd.com': '램바이디',
  'sansdoute.co.kr': '상두트',
  'monsterrepublic.co.kr': '몬스터리퍼블릭',
  'runningnose.kr': '러닝노즈',
  'ziosongzio.com': '지오송지오',
  'gucci.com': '구찌',
  'aboki.net': '아보키',
  'jogunshop.com': '조군샵',
  'maninstore.co.kr': '맨인스토어',
  'justsaturday.net': '저스트세러데이',
  'anolorcode.com': '어널러코드',
  'label-archive.com': '라벨아카이브',
  'the-nohant.com': '노앙',
  'chrischristy.com': '크리스크리스티',
  'nomanual-official.com': '노매뉴얼',
  'wvproject.co.kr': '더블유브이프로젝트',
  'fennec.co.kr': '페넥',
  'lwoowl.co.kr': 'owl91',
  'overtheone.com': '오버더원',
  'outdoorproducts.kr': '아웃도어 프로덕츠',
  'mrpokerface.co.kr': '포커페이스',
  'countrypowder.com': '컨츄리파우더',
  'slowacid.com': '슬로우애시드',
  'yanthirteen.com': '얀13',
  'grooverhyme.co.kr': '그루브라임',
  'compagno.co.kr': '꼼파뇨',
  'vastic.co.kr': '바스틱',
  'lomort.co.kr': '소버먼트',
  'thetrillion.co.kr': '트릴리온',
  'freitag.ch': '프라이탁',
  'thestori.com': '더스토리',
  'lab12.co.kr': '랩12',
  'rolarola.com': '로라로라',
  'litstore.kr': '리트',
  'zplish.com': '지플리시',
  'uniis-design.com': '유니스디자인',
  'vtz.co.kr': '베테제',
  'deutero.co.kr': '듀테로',
  'lacoste.com': '라코스테',
  'phos333.com': '포스333',
  'gu-global.com': 'GU',
  'fredperrykorea.com': '프레디페리',
  'shop.reebok.co.kr': '리복',
  'onitsukatiger.com': '오니츠카 타이거',
  'topten.topten10mall.com': '탑텐',
  'neweracapkorea.com': '뉴에라',
  'nepamall.com': '네파',
  'skonoshop.com': '스코노',
  'dynafit.co.kr': '다이나핏',
  'jansportkorea.co.kr': '잔스포츠',
  'blackyak.com': '블랙야크',
  'dickiesmall.co.kr': '디키즈',
  'kappakorea.net': '카파',
  'mskn2nd.com': '문수권세컨',
  'kangolkorea.com': '캉골',
  'emart.ssg.com': '데이즈',
  'shop.mango.com': '망고',
  'stylenanda.com': '스타일난다',
  'kr.mcmworldwide.com': 'MCM',
  'stylelq.com': '루이까또즈',
  'seikoboutique.co.kr': '세이코',
  'ayoungcompany.com': '아영상사',
  'bottegaveneta.com': '보테가 베네타',
  'haruta.co.kr': '하루타',
  'montblanc.com': '몽블랑',
  'givenchy.com': '지방시',
  'ysl.com': '생로랑',
  'moncler.com': '몽클레어',
  'apc-korea.com': '아페쎄',
  'acnestudios.com': '아크네스튜디오',
  'kr.burberry.com': '버버리',
  'stoneisland.com': '스톤아일랜드',
  'mooseknuckleskorea.com': '무스너클',
  'dior.com': '디올',
  'humant.kr': '후망',
  'steadyeverywear.com': '스테디 에브리웨어',
  'haharchive.com': '하 아카이브',
  '1507.co.kr': '일오공칠',
  'shop.timberland.co.kr': '팀버랜드',
  'gentlemonster.com': '젠틀몬스터',
  'not4nerd.net': '낫포너드',
  'acha1.com': '아차',
  'betterthan88.com': '베러댄88',
  'konusbrand.co.kr': '코너스',
  'badinbad.com': '배드인배드',
  'coucou-store.com': '코우코우',
  'clotty.co.kr': '클로티',
  'ourscope.co.kr': '아워스코프',
  'findkapoor.com': '파인드카푸어',
  'instantfunk.co': '인스턴트펑크',
  'outstanding-co.kr': '아웃스탠딩',
  'doubleloversroom.com': '더블러버스',
  'derobe.kr': '드로브',
  'oofos.co.kr': '우포스',
  'sonamustore.com': '디미트리블랙',
  'dprique.com': '디프리크',
  'ssolant.com': '쏠란트',
  'filsonkorea.co.kr': '필슨',
  'savage.co.kr': '세비지',
  'waar.co.kr': '와르',
  'patagonia.co.kr': '파타고니아',
  'code-graphy.com': '코드그라피',
  'burningstudios.co.kr': '버닝스튜디오',
  'oohahh.co.kr': '우아',
  'varzar.com': '바잘',
  'byc.co.kr': 'BYC',
  'thesortie.com': '솔티',
  'kr.moscot.com': '모스콧',
  'deadendkr.cafe24.com': '데드엔드',
  'shop.amoebaculture.com': '아메바컬쳐',
  'rockingag.com': '락킹에이지',
  'fillike.com': '필리케',
  'cottonbell.co.kr': '코튼벨',
  'aspivot.com': '에스파이벗',
  'madgoat-official.com': '매드고트',
  'oddoneout.co.kr': '오드원아웃',
  'roccirocci.com': '로씨로씨',
  'ojos.kr': '오호스',
  'ames-worldwide.com': '아메스월드와이드',
  'ballute.co.kr': '발루트',
  'letterfrommoon.com': '레터프롬문',
  'hyoji.co.kr': '효지노리코',
  'fanacult.com': '파나컬트',
  'nordstudio.co.kr': '노드스튜디오',
  'k-ing.kr': '킹아카이브',
  '13month.com': '써틴먼스',
  'aqostudio.com': '아코스튜디오스페이스',
  'fuza.world': '퓨자',
  'easestore.co.kr': '이즈',
  'esfai.co.kr': '에스파이',
  'nodearchive.com': '노드아카이브',
  'dgre.co.kr': '디그레',
  'waze8690s.cafe24.com': '웨이즈',
  'chindown.kr': '친다운',
  'edenmade.co.kr': '이든메이드',
  'oryany.co.kr': '오야니뉴욕',
  'joesnewbalanceoutlet.com': '뉴발란스',
  'enou.co.kr': '에노우',
  'adlielos.com': '에드리엘로스',
  'solidhomme.com': '솔리드옴므',
  'biflapper.com': '바이플래퍼',
  'attention-row.com': '어텐션로우',
  'brans.kr': '브랜즈',
  'roughside.co.kr': '러프사이드',
  'ptry.co.kr': '포터리',
  'routeoneshoes.co.kr': '루트원슈즈',
  'lotuff.co.kr': '로터프',
  'sculptorpage.com': '스컬프터',
  'polyteru-store.com': '폴리테루',
  'kutletshop.com': '비얼디드키드',
  'wuzustudio.com': '우주스튜디오',
  'amfeast.co.kr': '암피스트',
  'ohkoos.com': '빅유니온',
  'overr.co.kr': '오베르',
  'auction.co.kr': '옥션',
  'alexandermcqueen.com': '알렉산더맥퀸',
  'mooseknucklescanada.kr': '무스너클',
  'waikei.co.kr': '와이케이',
  'ffai.co.kr': '파이',
  'espionage.co.kr/m': '에스피오나지',
  'aecawhite.com': '에이카화이트',
  'apple.com': '애플',
  'haharchive.net': '하 아카이브',
  'uniongarments.co.kr': '유니온가먼츠',
  'perenn.co.kr': '퍼렌',
  'blond9.com': '블론드나인',
  'ourlegacy.se': '아워레가시',
  'longvaca.kr': '롱바케',
  'ovcworks.com': '오버캐스트',
  'intempomoode.com': '인템포무드',
  'worthwhilemovement.com': '월스와일 무브먼트',
  'riseandbelow.com': '라이즈앤빌로우',
  'kaneitei.com': '카네이테이',
  'begin202.com': '비긴 202',
  'pemont.me': '페몬트',
  'vacant.kr': '베이컨트',
  'mamagari.com': '마마가리',
  'samsonite.co.kr': '쌤소나이트',
  'newcheapchic.store': '뉴치프시크',
  'thefabric.kr': '더패브릭',
  'concepts1one.co.kr': '컨셉원',
  'maveworks.com': '메이브',
  'd-answer.com': '디앤써',
  'amekaji-moaa.com': '모아',
  'googongfast.com': '구공페스트',
  'nsad-official.com': 'NSAD*',
};

// brandKorAlias의 key값 형식은 영문브랜드명에서 영문, 숫자 외 모든 문자를 제거한 소문자입니다.
export const brandKorAlias = {
  '6ft': '식스핏',
  acnestudios: '아크네스튜디오',
  adidas: '아디다스',
  aecawhite: '에이카화이트',
  afterpray: '애프터프레이',
  alexandermcqueen: '알랙산더 맥퀸',
  ancientgreeksandals: '에인션트 그릭 샌들',
  antisocialsocialclub: '안티소셜소셜클럽',
  apc: '아페쎄',
  apcmen: '아페쎄 맨',
  apcwomen: '아페쎄 우먼',
  asics: '아식스',
  atelierkhj: '아뜰리에 케이에이치제이',
  auralee: '오라리',
  balenciaga: '발렌시아가',
  baracuta: '바라쿠타',
  bauhausarchiv: '바우하우스',
  berenice: '베르니스',
  birkenstock: '버켄스탁',
  birthdaysuit: '벌스데이수트',
  blankof: '블랭코브',
  boglioli: '볼리올리',
  bonnesuit: '보네 수트',
  bottegaveneta: '보테가베네타',
  brownyard: '브라운야드',
  brunellocucinelli: '브루넬로쿠치넬리',
  bsqt: 'bsqt',
  buffalo: '버팔로',
  buffalolondon: '버팔로 런던',
  burberry: '버버리',
  catchball: '캐치볼',
  camielfortgens: '카미엘 포트겐스',
  carharttwip: '칼하트 wip',
  champion: '챔피온',
  chlo: '끌로에',
  chloestora: '끌로에 스토라',
  churchs: '처치스',
  clamp: '클램프',
  class: '클래스',
  claudiepierlot: '끌로디 피에로',
  clayong: '클레용',
  commonproject: '커먼 프로젝트',
  commonprojects: '커먼프로젝트',
  converse: '컨버스',
  crocs: '크록스',
  debonnefacture: '드 보네 팩터',
  dior: '디올',
  document: '도큐먼트',
  dolcegabbana: '돌체앤가비나',
  donjuan: '돈후안',
  doucals: '도우칼스',
  driesvannoten: '드리스 반 노튼',
  drmartens: '닥터마틴',
  drumohr: '드루모어',
  dsquared2: '디스퀘어드2',
  eastlogue: '이스트로그',
  eleventy: '일레븐티',
  eleventymen: '엘레벤티 맨',
  eleventywomen: '엘레벤티 우먼',
  engineeredgarments: '엔지니어드가먼츠',
  ernestwbaker: '어니스트베이커',
  essentiel: '에센셜',
  etautz: '이타우즈',
  etro: '에트로',
  fila: '휠라',
  fogessentials: 'fog 에센셜 후드',
  fredperry: '프레드페리',
  givenchy: '지방시',
  givy: '기비',
  goldengoose: '골든구스',
  goldengoosedeluxebrand: '골든구스 디럭스 브랜드',
  gonesh: '고네쉬',
  graphpaper: '그라프페이퍼',
  gucci: '구찌',
  head: '헤드',
  hotel990: '호텔990',
  iabstudio: '아이앱 스튜디오',
  idea: '아이디어',
  ilbisonte: '일 비종떼',
  isabelmarant: '이자벨마랑',
  isabelmaranttoile: '이자벨마랑 에뚜왈',
  ivsi: '아이비즈아이',
  jilsander: '질 샌더',
  jimmychoo: '지미 추',
  jordan: '조던',
  juanhomme: '주앙옴므',
  keith: '키이스',
  kenzo: '겐조',
  kimclothing: '킴클로딩',
  lacoste: '라코스테',
  lemine: '르마인',
  loewe: '로에베',
  magazineb: '매거진비',
  maisonmargiela: '메종 마르지엘라',
  maje: '마쥬',
  malibusandals: '말리부샌들',
  manoloblahnik: '마놀로 블라닉',
  marimekko: '마리에꼬',
  marni: '마르니',
  marsll: '마르셀',
  marvel: '마블',
  mfpen: '엠에프펜',
  miharayasuhiro: '미하라야스히로',
  mlb: 'mlb',
  msgm: '엠에스지엠',
  nanamica: '나나미카',
  needles: '니들스',
  neithers: '네이더스',
  nerdy: '널디',
  newbalance: '뉴발란스',
  nhoolywood: '엔 헐리우드',
  nike: '나이키',
  officinecreative: '오피치네 크레아티베',
  offwhite: '오프화이트',
  oofos: '우포스',
  ourlegacy: '아워레가시',
  palace: '팔라스',
  patagonia: '파타고니아',
  prada: '프라다',
  puebco: '푸에브코',
  puma: '푸마',
  redwing: '레드윙',
  reebok: '리복',
  reneevon: '레니본',
  reproductionoffound: '리프로덕션오브파운드',
  rickowens: '릭 오웬스',
  romanticmove: '로맨틱무브',
  saintlaurent: '생로랑',
  salomon: '살로몬',
  salvatoreferragamo: '살바토레 페레가모',
  sandro: '산드로',
  sandrohomme: '산드로 옴므',
  santoni: '산토니',
  skechers: '스케처스',
  skono: '스코노',
  slickandeasy: '슬릭앤이지',
  slowsteadyclub: '슬로우 스테디 클럽',
  stellamccartney: '스텔라 매카트니',
  stoneisland: '스톤 아일랜드',
  stuartweitzman: '스튜어트 와이츠먼',
  studionicholson: '스튜디오 니콜슨',
  stussy: '스투시',
  superga: '수페르가',
  supreme: '슈프림',
  technica: '테크니카',
  teva: '테바',
  thenorthface: '노스페이스',
  thombrowne: '톰 브라운',
  tods: '토즈',
  unaffected: '언어펙티드',
  uniformbridge: '유니폼브릿지',
  valentino: '발렌티노',
  vans: '반스',
  versace: '베르사체',
  americantourister: '아메리칸투어리스터',
  gregory: '그레고리',
  highsierra: '하이시에라',
  kamiliant: '카밀리안트',
  lipault: '리뽀',
};

export const getBrandKor = (brandEng: string): string => {
  return (
    brandKorAlias[brandEng.toLowerCase().replace(/[^a-zA-z0-9]/, '')] ||
    brandEng
  );
};
